"""empty message

Revision ID: 41f43b603a0
Revises: 3d7a59e1925
Create Date: 2015-05-01 15:55:44.300823

"""

# revision identifiers, used by Alembic.
revision = '41f43b603a0'
down_revision = '3d7a59e1925'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('redirect_url', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'redirect_url')
    ### end Alembic commands ###
